MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from usuarios import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls.base import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from MeuSite.views import visualizaTelaHome
from usuarios.views import (
    registrarUsuario,
    visualizaLogout,
    visualizaLogin,
    visualizaUsuario,
    visualizaDeletaUsuario,
    visualizaAutentica
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', visualizaTelaHome, name='home'),
    path('registro/', registrarUsuario, name = "registro"),
    path('login/', visualizaLogin, name = "login"),
    path('logout/', visualizaLogout, name = "logout"),
    path('usuario/', visualizaUsuario, name = "usuario"),
    path('deleta_usuario/', visualizaDeletaUsuario, name = "deleta_usuario"),
    path('filme/', include('filmes.urls', 'filmes')),
    path('must_authenticate/', visualizaAutentica, name = "deveAutenticar"),
    path('muda_senha/done/', auth_views.PasswordChangeView.as_view(template_name='registro/password_change_done.html'), 
         name='password_change_done'),
    path('muda_senha/', auth_views.PasswordChangeView.as_view(template_name='registro/mudaSenha.html'), 
         name='muda_senha'),
    path('recupera_senha/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaSenhaDone.html'), 
         name='recupera_senha_done'),
    path('recupera_senha/', auth_views.PasswordResetView.as_view(), 
         name='recupera_senha'),    
    path('recupera/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
         name='recupera_confirma'),
    path('recupera/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaCompleto.html'), 
         name='recupera_completa'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

MeuSite/filmes/urls.py
from django.urls import path

from filmes.views import (
    postaFilmeView,
    editaFilmeView,
    apagaFilmeView,
    detalhaFilmeView,
    
)

app_name = 'filmes'

urlpatterns = [
    path('posta/', postaFilmeView, name = "posta" ),
    path('<slug>/edita',editaFilmeView, name = "edita" ),
    path('<slug>/delete', apagaFilmeView, name ="apaga" ),
    path('<slug>/', detalhaFilmeView, name = "detalha")
    
]

MeuSite/usuarios/urls.py
from django.urls.conf import path
from usuarios import views

app_name = "usuarios"

urlpatterns = [

]

MeuSite/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AdminMinhaConta(BaseUserManager):

    def create_user(self, email, username, password = None):
        if not email:
            raise ValueError("Usuario precisa ter um endereço de email")
        if not username:
            raise ValueError("Usuario precisa ter um nome")

        user = self.model(
                email = self.normalize_email(email),
                username = username,

        )

        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_superuser(self,email,username, password):

        user = self.create_user(
                email = self.normalize_email(email),
                password = password,
                username = username,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user

class Usuario(AbstractBaseUser):

    id = models.AutoField(primary_key=True, null=False, blank=False)

    username = models.CharField(help_text='Entre o nome', 
                            max_length=100, null=False, blank=False)
    
    idade = models.IntegerField(help_text='Entre a idade', null=True, blank=True)

    
    email = models.EmailField(help_text='Informe o email',
                              max_length=254, null=False, blank=False, unique=True)
    
    is_admin = models.BooleanField(default=False)
    
    is_active = models.BooleanField(default=True)
    
    is_staff = models.BooleanField(default=False)
    
    is_superuser = models.BooleanField(default=False)

    
    objects= AdminMinhaConta()
    

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username',]
    
    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj = None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True

MeuSite/usuarios/forms.py
from django import forms
from usuarios.models import Usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from typing import Any


class UsuarioRegistraForm(UserCreationForm):

    email = forms.EmailField(max_length=60, help_text="Obrigatório. Entre com o seu email")

    class Meta:
        model = Usuario
        fields = ('email', 'username', 'password1', 'password2')

class UsuarioAutenticaForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Usuario
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password = password):
                raise forms.ValidationError("Login Inválido")
            
class UsuarioAtualizaForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ('email','username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                usuario = Usuario.objects.exclude(pk=self.instance.pk).get(email=email)
            except Usuario.DoesNotExist:
                 return email
            raise forms.ValidationError('Email "%s" já sendo utilizado.' % email)
        
    def clean_nome(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                usuario = Usuario.objects.exclude(pk=self.instance.pk).get(username=username)
            except Usuario.DoesNotExist:
                 return username
            raise forms.ValidationError('Nome "%s" já sendo utilizado.' % username)
        

MeuSite/usuarios/views.py
from usuarios.models import Usuario
from django.views.generic.base import View
from usuarios.forms import UsuarioRegistraForm
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from usuarios.forms import UsuarioRegistraForm
from usuarios.forms import UsuarioAutenticaForm, UsuarioAtualizaForm
from django.contrib import messages
from filmes.forms import Filme
from operator import attrgetter
from django.conf import settings
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
    

def registrarUsuario(request):
    contexto = {}
    if request.POST:
          form = UsuarioRegistraForm(request.POST)
          if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password_k = form.cleaned_data.get('password1')
            usuario = authenticate(email=email, password=password_k)
            login(request, usuario)
            return redirect('home')
          else:
              contexto['registration_form'] = form
    else:
        form = UsuarioRegistraForm()
        contexto['registration_form'] = form
    
    return render(request, 'usuarios/registro.html', contexto)


def visualizaLogout(request):
    logout(request)
    messages.success(request, 'Logout feito com sucesso!')
    return redirect('home')


def visualizaLogin(request):
    print('c')
    contexto = {}

    user = request.user
    if user.is_authenticated:
        return redirect('home')
    
    if request.POST:
        print('c')
        form = UsuarioAutenticaForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email = email, password=password)
            print('a')
            
            if user:
                print('b')
                login(request,user)
                messages.success(request, 'Login feito com sucesso!') 
                return redirect("home")
            
    else:
        form = UsuarioAutenticaForm()
        
    contexto['login_form'] = form
    return render(request, 'usuarios/login.html', contexto)


def visualizaUsuario(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    contexto = {}

    if request.POST:
        form = UsuarioAtualizaForm(request.POST, instance=request.user)
        if form.is_valid():
            form.initial = {
				"email": request.POST['email'],
				"username":request.POST['username'],
			}
            form.save()
            messages.success(request, 'Conta atualizada com sucesso!')
        else:
            messages.warning(request, 'E-mail ou usuário indisponíveis. Tente novamente.')
    else:
        form = UsuarioAtualizaForm(
            initial={
				"email": request.user.email,
				"username": request.user.username,
			}
        )

    contexto['usuario_form'] = form
    filme = sorted(Filme.objects.filter(usuario=request.user), key=attrgetter('titulo'), reverse=True)
    contexto['filmes'] = filme

    pagina = request.GET.get("pagina",1)
    filmesEmPaginas = Paginator(filme, settings.FILMES_PER_PAGE)

    try:
        filme = filmesEmPaginas.page(pagina)
    except PageNotAnInteger:
        filme = filmesEmPaginas.page(settings.FILMES_PER_PAGE)
    except:
        filme = filmesEmPaginas.page(filmesEmPaginas.num_pages)

    contexto['filmes'] = filme
    return render(request,'usuarios/usuario.html', contexto)

def visualizaDeletaUsuario(request):

    if not request.user.is_authenticated:
        return redirect("login")
    
    contexto = {}

    if request.POST:
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(email = request.user.email, password = password)

        if user:
            user.delete()
            messages.success(request, 'Conta deletada com sucesso!')
            return redirect("home")
        else:
            messages.warning(request, 'Usuário ou senha incorretos. Tente novamente.')

    return render(request, 'usuarios/deletaUsuario.html', contexto)


def visualizaAutentica(request):
	return render(request,"usuarios/deveAutenticar.html",{})

MeuSite/usuarios/templates/usuarios/deletaUsuario.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7 mx-auto my-5">
            <div class="card mx-auto my-5">
                <div class="card-header">
                    <h3 class="text-center">Apagar sua conta</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3 text-center">
                            <h3>Tem certeza que deseja apagar sua conta?</h3>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="text" name="email" class="form-control" id="email" placeholder="Digite seu email" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Senha</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha" required>
                        </div>
                        {% if failed_message %}
                        <p style="color: red; text-align: center;">{{ failed_message }}</p>
                        {% endif %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Apagar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

MeuSite/usuarios/templates/usuarios/deveAutenticar.html
{% extends 'base.html' %}

{% block content %}

<title>Movie Tracker</title>

<div class="container">
	<div class="alert alert-warning" style = "margin-top: 50px;">
		<p class="text-center" style="margin-top: 10px;">Você deve estar logado!</p>
        <p class="text-center" style="margin-top: 10px;"> Redirecionando para o Login em 3 segundos.</p>
	</div>
</div>

<meta http-equiv="refresh" content="3;{% url 'login' %}">

{% endblock %}

MeuSite/usuarios/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>Movie Tracker</title>

<div class="container">
    <div class="d-flex flex-column" style="margin-bottom: 20px;">
        <img class="img-fluid mx-auto" src="{% static 'Movie_Tracker_Logo.png'%}" alt="Movie Tracker - Avalie seus filmes" width="400" height="20" style="margin-top: 30px;">
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 mx-auto my-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Login</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="email">e-mail</label>
                                <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail" required>
                            </div>
                            <div class="mb-3">
                                <label for="password">Senha</label>
                                <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha" required>
                            </div>
                            {% for field in login_form %}
                            <p>
                                {% for error in field.errors %}
                                <p style="color: red;">{{ error }}</p>
                                {% endfor %}
                            </p>
                            {% endfor %}
                            {% if login_form.non_field_errors %}
                            <div style="color: red;">
                                <p>{{ login_form.non_field_errors }}</p>
                            </div>
                            {% endif %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Entrar</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <p>Crie sua conta! <a href="{% url 'registro' %}">Cadastre-se</a></p>
                        <p>Esqueceu sua senha? <a href="{% url 'recupera_senha' %}">Redefinir Senha</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

MeuSite/usuarios/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>Movie Tracker</title>

<div class="container">
    <div class="d-flex flex-column" style="margin-bottom: 20px;">
        <img class="img-fluid mx-auto" src="{% static 'Movie_Tracker_Logo.png'%}" alt="Movie Tracker - Avalie seus filmes" width="400" height="20" style="margin-top: 30px;">
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 mx-auto my-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Registrar</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="email" class="form-label">e-mail</label>
                                <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail" required>
                            </div>
                            <div class="mb-3">
                                <label for="username" class="form-label">Usuário</label>
                                <input type="text" name="username" class="form-control" id="username" placeholder="Digite seu usuario" required>
                            </div>
                            <div class="mb-3">
                                <label for="password1" class="form-label">Senha</label>
                                <input type="password" name="password1" class="form-control" id="password1" placeholder="Digite sua senha" required>
                            </div>
                            <div class="mb-3">
                                <label for="password2" class="form-label">Confirmação de senha</label>
                                <input type="password" name="password2" class="form-control" id="password2" placeholder="Confirme sua senha" required>
                            </div>
                            {% for field in registration_form %}
                            <p>
                                {% for error in field.errors %}
                                <p style="color: red;">{{ error }}</p>
                                {% endfor %}
                            </p>
                            {% endfor %}
                            {% if registration_form.non_field_errors %}
                            <div style="color: red;">
                                <p>{{ registration_form.non_field_errors }}</p>
                            </div>
                            {% endif %}

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Registrar</button>
                            </div>

                        </form>
                    </div>               
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

MeuSite/usuarios/templates/usuarios/usuario.html
{% extends 'base.html' %}

{% block content %}

<title>Conta de {{user}}</title>

<div class="container mt-4">
    <div class="row">
        <!-- Coluna para os posts no centro da tela -->
        <div class="col-md-7">
            <h3 class="mb-2 font-weight-normal" style="color: white;">Seus Filmes:</h3>
            {% if filmes %}
                <ul class="list-group">
                    {% for filme in filmes %}
                        <div class="filme-post-container mt-3">
                            {% include 'partes/partesFilme.html' with filme=filme %}
                        </div>
                    {% endfor %}
                </ul>
            {% else %}
                <ul class="list-group">
                    <div>
                        <li class="list-group-item d-flex justify-content-center">
                            <div>
                                <a href="{% url 'filmes:posta' %}" style="text-decoration: none !important" class="stretched-link link-dark">Você não listou nenhum filme. Quer adicionar?</a>
                            </div>
                        </li>
                    </div>
                </ul>
            {% endif %}
        </div>
        
        <!-- Coluna para o formulário de mudança de email e senha (menor) -->
        <div class="col-md-5 mt-2 ">
            <div class="card offset-md-2 mt-5 text-bg-dark">
                <div class="card-header">
                    <h3 class="text-center">Conta</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3 ">
                            <label for="email" class="form-label ">Novo email:</label>
                            <input type="email" name="email" class="form-control text-bg-dark" id="email" placeholder="Digite seu novo e-mail" value="{{ account_form.initial.email }}">
                        </div>
                        <div class="mb-3">
                            <label for="username" class="form-label">Novo Username:</label>
                            <input type="text" name="username" class="form-control text-bg-dark" id="username" placeholder="Digite seu novo Username" value="{{ account_form.initial.username }}">
                        </div>

                        {% for field in usuario_form %}
                            <p>
                                {% for error in field.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                {% endfor %}
                            </p>
                        {% endfor %}

                        {% if usuario_form.non_field_errors %}
                            <div style="color: red;">
                                <p>{{ usuario_form.non_field_errors }}</p>
                            </div>
                        {% endif %}

                        <div class="d-flex flex-column">
                            <a class="m-auto" href="{% url 'muda_senha' %}">Mudança de senha</a>
                        </div>

                        <div class="mt-3 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Salvar mudanças</button>
                            <a role="button" href="{% url 'deleta_usuario' %}" class="btn btn-danger">Apagar conta</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% include 'partes/paginationFilme.html' with filmes=filmes %}
    </div>
</div>


{% endblock content %}