MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from usuarios import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls.base import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from MeuSite.views import visualizaTelaHome
from usuarios.views import (
    registrarUsuario,
    visualizaLogout,
    visualizaLogin,
    visualizaUsuario,
    visualizaDeletaUsuario,
    visualizaAutentica
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', visualizaTelaHome, name='home'),
    path('registro/', registrarUsuario, name = "registro"),
    path('login/', visualizaLogin, name = "login"),
    path('logout/', visualizaLogout, name = "logout"),
    path('usuario/', visualizaUsuario, name = "usuario"),
    path('deleta_usuario/', visualizaDeletaUsuario, name = "deleta_usuario"),
    path('filme/', include('filmes.urls', 'filmes')),
    path('must_authenticate/', visualizaAutentica, name = "deveAutenticar"),
    path('muda_senha/done/', auth_views.PasswordChangeView.as_view(template_name='registro/password_change_done.html'), 
         name='password_change_done'),
    path('muda_senha/', auth_views.PasswordChangeView.as_view(template_name='registro/mudaSenha.html'), 
         name='muda_senha'),
    path('recupera_senha/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaSenhaDone.html'), 
         name='recupera_senha_done'),
    path('recupera_senha/', auth_views.PasswordResetView.as_view(), 
         name='recupera_senha'),    
    path('recupera/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
         name='recupera_confirma'),
    path('recupera/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaCompleto.html'), 
         name='recupera_completa'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

MeuSite/filmes/urls.py
from django.urls import path

from filmes.views import (
    postaFilmeView,
    editaFilmeView,
    apagaFilmeView,
    detalhaFilmeView,
    
)

app_name = 'filmes'

urlpatterns = [
    path('posta/', postaFilmeView, name = "posta" ),
    path('<slug>/edita',editaFilmeView, name = "edita" ),
    path('<slug>/delete', apagaFilmeView, name ="apaga" ),
    path('<slug>/', detalhaFilmeView, name = "detalha")
    
]

MeuSite/filmes/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver

def localiza(instance,filename):
    
    path = 'filme/{usuario_id}/{titulo}-{filename}'.format(
        usuario_id=str(instance.usuario.id), titulo = str(instance.titulo), filename = filename
        )
    
    return path

class Filme(models.Model):
    titulo = models.CharField(help_text='Digite o titulo do filme', 
                              max_length=50, null=False, blank=False)
    nacionalidade = models.CharField(help_text='Digite a nacionalidade do filme', 
                              max_length=50, null=False, blank=False)
    ano = models.CharField(help_text='Digite o ano de lancamento do filme', 
                              max_length=50, null=False, blank=False)
    sinopse = models.CharField(help_text='Digite o titulo do filme', 
                              max_length=200, null=True, blank=True)
    diretor = models.CharField(help_text='Digite o nome do diretor', 
                              max_length=50, null=False, blank=False)
    nota = models.CharField(help_text='Digite a nota que avalia o filme', 
                              max_length=50, null=True, blank=True)
    review = models.CharField(help_text='Digite um breve review do filme', 
                              max_length=200, null=True, blank=True)
    visto = models.BooleanField(default=False)
    
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    slug = models.SlugField(blank=True, unique=True)
    
    def __str__(self):
        return self.titulo
    
@receiver(post_delete, sender=Filme)
def salva_recebe_filme(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.usuario.username + "-" + instance.titulo)

pre_save.connect(salva_recebe_filme, sender=Filme)
    

MeuSite/filmes/forms.py
from django import forms

from filmes.models import Filme

class InsereFilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['titulo', 'nacionalidade', 'ano', 'sinopse', 'diretor', 
                  'nota', 'review', 'visto']
        
class AtualizaFilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['titulo', 'review', 'nota']
        
        def salva(self, commit = True):
            filmeInsert = self.instance
            filmeInsert.titulo = self.cleaned_data['titulo']
            filmeInsert.nacionalidade = self.cleaned_data['nacionalidade']
            filmeInsert.ano = self.cleaned_data['ano']
            filmeInsert.sinopse = self.cleaned_data['sinopse']
            filmeInsert.diretor = self.cleaned_data['diretor']
            filmeInsert.nota = self.cleaned_data['nota']
            filmeInsert.review = self.cleaned_data['review']
            filmeInsert.visto = self.cleaned_data['visto']
            
            if commit:
                filmeInsert.save()
            
            return filmeInsert

MeuSite/filmes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from filmes.forms import InsereFilmeForm, AtualizaFilmeForm
from usuarios.models import Usuario
from django.contrib import messages
from filmes.models import Filme

def postaFilmeView(request):
    context ={}
    
    user = request.user
    if not user.is_authenticated:
        return redirect('deveAutenticar')
    
    form = InsereFilmeForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        objeto = form.save(commit=False)
        usuario = Usuario.objects.filter(email=user.email).first()
        objeto.usuario = usuario
        objeto.save()
        form = InsereFilmeForm()
        messages.success(request, 'Filme adicionado!')
        return redirect('home')
    
    context['form'] = form
    return render(request, "filmes/postaFilme.html", context)

def apagaFilmeView(request, slug):
    context = {}
    filme = get_object_or_404(Filme, slug=slug)
    
    if request.POST:
        filme.delete()
        messages.success(request, 'Filme retirado!')
        return redirect('home')
    
    context['filme'] = filme
    return render(request, 'filmes/apagaFilme.html', context)

def editaFilmeView(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('deveAutenticar')
    filme = get_object_or_404(Filme, slug=slug)
    if request.POST:
        form = AtualizaFilmeForm(request.POST or None, request.FILES or 
                                 None, instance=filme)
        if form.is_valid():
            objeto = form.save(commit=False)
            objeto.save()
            messages.success(request, 'Informações do filme atualizadas!')
            filme = objeto
            return redirect('home')
        
    form = AtualizaFilmeForm(
        initial= {
            "titulo": filme.titulo,
            "nacionalidade": filme.nacionalidade,
            "ano": filme.ano,
            "sinopse": filme.sinopse,
            "diretor": filme.diretor,
            "nota": filme.nota,
            "review": filme.review,
            "visto": filme.visto
        }
    )
    context['form'] = form
    return render(request, 'filmes/editaFilme.html', context)
            

def detalhaFilmeView(request,slug):
    contexto={}
    filme=get_object_or_404(Filme,slug=slug)
    contexto['filme']=filme
    return render(request, 'filmes/detalhaFilme.html' ,contexto)

MeuSite/filmes/templates/filmes/apagaFilme.html
{% extends 'base.html' %}

{% block content %}

<div class ='container'>
    <div class='row'>
        <form method='post' enctype='multipart/form-data'>
            {% csrf_token %}
            <div class='card m-auto mt-4' style='width: 900px'>
                <div class='card-body my-2'>
                    <h3 class='text-center'>Tem certeza que deseja retirar o filme?</h3>
                    <hr>
                    {% if filme.usuario == request.user %}
                    <div class='d-flex justify-content-between align-items-center'>
                        <h2 class='card-title'>{{filme.titulo}}</h2>
                    </div>
                    <hr>
                    <div class='container'>
                        <p class='card-text'>{{filme.nacionalidade}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-number'>{{filme.ano}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-text'>{{filme.sinopse}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-text'>{{filme.diretor}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-number'>{{filme.nota}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-text'>{{filme.review}}</p>
                    </div>
                    <div class='container'>
                        <p class='card-checkbox'>{{filme.visto}}</p>
                    </div>
                    <div class="mt-3 text-center">
                        <button type="submit" class="btn btn-danger">Deletar filme</button> 
                    </div>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content%}

MeuSite/filmes/templates/filmes/detalhaFilme.html
{% extends 'base.html' %}

{% block content %}

    <title>{{filme.titulo}}</title>

    <div class='container'>
        <div class='row'>
            <div class='card m-auto mt-4 text-bg-dark' style='width: 900px;'>
                <div class='card-body my-2'>
                    <p class="card-text text-bg-dark">{{filme.nacionalidade}}</p>
                    <p class="card-text text-bg-dark">{{filme.ano}}</p>
                    <p class="card-text text-bg-dark">{{filme.sinopse}}</p>
                    <p class="card-text text-bg-dark">{{filme.diretor}}</p>
                    <p class="card-text text-bg-dark">{{filme.nota}}</p>
                    <p class="card-text text-bg-dark">{{filme.review}}</p>
                    <p class="card-text text-bg-dark">{{filme.visto}}</p>
                    <div class='opsFilmes'>
                        {% if filme.usuario == request.user %}
                        <div class='ops'>
                            <a href='{% url 'filmes:edita' filme.slug %}' class='btn btn-warning mx-2'>Editar Filme</a>
                            <a href='{% url 'filmes:apaga' filme.slug %}'class='btn btn-danger'>Deletar Filme</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

MeuSite/filmes/templates/filmes/editaFilme.html
{% extends 'base.html' %}

{% block content %}

<title>Editar Filme{{filme.titulo}}</title>
<div class='container mt-2'>
    <div class ='row justify-content-center'>
        <div class='align-items-center'>
            <div class='card m-auto mt-4' style='width: 900px;'>
                <div class='card-header'>
                    <h3 class='text-center'>Editar filme</h3>
                </div>
                <div class='card-body'>
                    <form method='post' enctype='multipart/form-data'>
                        {% csrf_token %}
                        <div class='mb-3 form-group'>
                            <label for='id_titulo' class='form-label'>Título</label>
                            <input type='text' name='titulo' class='form-control' id='id_titulo' placeholder='Digite o titulo' value='{{form.initial.titulo}}' autofocus>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_nacionalidade' class='form-label'>Nacionalidade</label>
                            <input type='text' name='nacionalidade' class='form-control' id='id_nacionalidade' placeholder='Digite a nacionalidade' value='{{form.initial.nacionalidade}}' autofocus>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_ano' class='form-label'>Ano</label>
                            <input type='number' min='1900' max='2099' step='1' name='ano' class='form-control' id='id_ano' placeholder='Digite o ano' value='{{form.initial.ano}}' autofocus>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_sinopse' class='form-label'>Sinopse</label>
                            <textarea name='sinopse' class='form-control' id='id_sinopse' rows='10' placeholder='Digite a sinopse' value='{{form.initial.sinopse}}' autofocus></textarea>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_diretor' class='form-label'>Diretor</label>
                            <input type='text' name='diretor' class='form-control' id='id_diretor' placeholder='Digite o diretor' value='{{form.initial.diretor}}' autofocus>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_nota' class='form-label'>Nota</label>
                            <input type='number' name='nota' min='0' max='10' class='form-control' id='id_nota' placeholder='Digite sua nota' value='{{form.initial.nota}}' autofocus>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_review' class='form-label'>Review</label>
                            <textarea name='review' class='form-control' id='id_review' placeholder='Digite a review' value='{{form.initial.review}}' autofocus></textarea>
                        </div>
                        <div class='mb-3 form-group'>
                            <label for='id_visto' class='form-label'>Visto</label>
                            <input type='checkbox' name='visto' class='form-check-input' id='id_visto' placeholder='Marque se viu o filme' value='{{form.initial.visto}}' autofocus>
                        </div>
                        <div class='mt-3 d-flex justify-content-between'>
                            <button type='submit' class='btn btn-primary'>Atualiza Filme</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
</script>

{% endblock content %}

MeuSite/filmes/templates/filmes/postaFilme.html
{% extends 'base.html' %}
{% block content %}

<div class='container mt-5'>
    <div class='row justify-content-center'>
        <div class='col-md-6'>
            <div class='card'>
                <div class='card-header'>
                    <h3 class='text-center'>Posta Novo Filme</h3>
                </div>
                <div class='card-body'>
                    <form method='post' enctype='multipart/form-data'>
                        {% csrf_token %}
                        <div class='mb-3'>
                            <label for='id_titulo' class='form-label'>Título</label>
                            <input type='text' name='titulo' class='form-control' id='id_titulo' placeholder='Título' required autofocus>
                        </div>
                        <div class="mb-3">
                            <label for="id_nacionalidade" class="form-label">Nacionalidade</label>
                            <input type='text' name="nacionalidade" class="form-control" id="id_nacionalidade" placeholder="Qual a nacionalidade do filme?" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_ano" class="form-label">Ano</label>
                            <input type='number' name="ano" class="form-control" id="id_ano" placeholder="Qual ano foi lançado?" min='1900' max='2099' step='1' required>
                        </div>
                        <div class="mb-3">
                            <label for="id_sinopse" class="form-label">Sinopse</label>
                            <textarea name="sinopse" id="id_sinopse" rows="10" class="form-control" placeholder="Uma breve sinopse do filme"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="id_diretor" class="form-label">Diretor</label>
                            <input type='text' name="diretor" class="form-control" id="id_diretor" placeholder="Qual o diretor?" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_nota" class="form-label">Nota</label>
                            <input type='number' name="body" class="form-control" id="id_nota" placeholder="Qual sua nota?" min='0' max='10'>
                        </div>
                        <div class="mb-3">
                            <label for="id_review" class="form-label">Review</label>
                            <textarea name="review" id="id_review" rows="10" class="form-control" placeholder="Uma breve review"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="id_visto" class="form-label">Visto</label>
                            <input type='checkbox' name="visto" class="form-check-input" id="id_visto" placeholder="Você viu esse filme?">
                        </div>
                        <div class='text-center'>
                            <button type='submit' class='btn btn-primary'>Postar Filme</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}