MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from usuarios import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls.base import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from MeuSite.views import visualizaTelaHome
from usuarios.views import (
    registrarUsuario,
    visualizaLogout,
    visualizaLogin,
    visualizaUsuario,
    visualizaDeletaUsuario,
    visualizaAutentica
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', visualizaTelaHome, name='home'),
    path('registro/', registrarUsuario, name = "registro"),
    path('login/', visualizaLogin, name = "login"),
    path('logout/', visualizaLogout, name = "logout"),
    path('usuario/', visualizaUsuario, name = "usuario"),
    path('deleta_usuario/', visualizaDeletaUsuario, name = "deleta_usuario"),
    path('filme/', include('filmes.urls', 'filmes')),
    path('must_authenticate/', visualizaAutentica, name = "deveAutenticar"),
    path('muda_senha/done/', auth_views.PasswordChangeView.as_view(template_name='registro/password_change_done.html'), 
         name='password_change_done'),
    path('muda_senha/', auth_views.PasswordChangeView.as_view(template_name='registro/mudaSenha.html'), 
         name='muda_senha'),
    path('recupera_senha/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaSenhaDone.html'), 
         name='recupera_senha_done'),
    path('recupera_senha/', auth_views.PasswordResetView.as_view(), 
         name='recupera_senha'),    
    path('recupera/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
         name='recupera_confirma'),
    path('recupera/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registro/recuperaCompleto.html'), 
         name='recupera_completa'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

MeuSite/filmes/urls.py
from django.urls import path

from filmes.views import (
    postaFilmeView,
    editaFilmeView,
    apagaFilmeView,
    detalhaFilmeView,
    
)

app_name = 'filmes'

urlpatterns = [
    path('posta/', postaFilmeView, name = "posta" ),
    path('<slug>/edita',editaFilmeView, name = "edita" ),
    path('<slug>/delete', apagaFilmeView, name ="apaga" ),
    path('<slug>/', detalhaFilmeView, name = "detalha")
    
]

MeuSite/filmes/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver

def localiza(instance,filename):
    
    path = 'filme/{usuario_id}/{titulo}-{filename}'.format(
        usuario_id=str(instance.usuario.id), titulo = str(instance.titulo), filename = filename
        )
    
    return path

class Filme(models.Model):
    titulo = models.CharField(help_text='Digite o titulo do filme', 
                              max_length=50, null=False, blank=False)
    nacionalidade = models.CharField(help_text='Digite a nacionalidade do filme', 
                              max_length=50, null=False, blank=False)
    ano = models.CharField(help_text='Digite o ano de lancamento do filme', 
                              max_length=50, null=False, blank=False)
    sinopse = models.CharField(help_text='Digite o titulo do filme', 
                              max_length=200, null=True, blank=True)
    diretor = models.CharField(help_text='Digite o nome do diretor', 
                              max_length=50, null=False, blank=False)
    nota = models.CharField(help_text='Digite a nota que avalia o filme', 
                              max_length=50, null=True, blank=True)
    review = models.CharField(help_text='Digite um breve review do filme', 
                              max_length=200, null=True, blank=True)
    visto = models.BooleanField(default=False)
    
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    slug = models.SlugField(blank=True, unique=True)
    
    def __str__(self):
        return self.titulo
    
@receiver(post_delete, sender=Filme)
def salva_recebe_filme(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.usuario.username + "-" + instance.titulo)

pre_save.connect(salva_recebe_filme, sender=Filme)
    

MeuSite/filmes/forms.py
from django import forms

from filmes.models import Filme

class InsereFilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['titulo', 'nacionalidade', 'ano', 'sinopse', 'diretor', 
                  'nota', 'review', 'visto']
        
class AtualizaFilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['titulo', 'review', 'nota']
        
        def salva(self, commit = True):
            filmeInsert = self.instance
            filmeInsert.titulo = self.cleaned_data['titulo']
            filmeInsert.nacionalidade = self.cleaned_data['nacionalidade']
            filmeInsert.ano = self.cleaned_data['ano']
            filmeInsert.sinopse = self.cleaned_data['sinopse']
            filmeInsert.diretor = self.cleaned_data['diretor']
            filmeInsert.nota = self.cleaned_data['nota']
            filmeInsert.review = self.cleaned_data['review']
            filmeInsert.visto = self.cleaned_data['visto']
            
            if commit:
                filmeInsert.save()
            
            return filmeInsert

MeuSite/filmes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from filmes.forms import InsereFilmeForm, AtualizaFilmeForm
from usuarios.models import Usuario
from django.contrib import messages
from filmes.models import Filme

def postaFilmeView(request):
    context ={}
    
    user = request.user
    if not user.is_authenticated:
        return redirect('deveAutenticar')
    
    form = InsereFilmeForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        objeto = form.save(commit=False)
        usuario = Usuario.objects.filter(email=user.email).first()
        objeto.usuario = usuario
        objeto.save()
        form = InsereFilmeForm()
        messages.success(request, 'Filme adicionado!')
        return redirect('home')
    
    context['form'] = form
    return render(request, "filmes/postaFilme.html", context)

def apagaFilmeView(request, slug):
    context = {}
    filme = get_object_or_404(Filme, slug=slug)
    
    if request.POST:
        filme.delete()
        messages.success(request, 'Filme retirado!')
        return redirect('home')
    
    context['filme'] = filme
    return render(request, 'filmes/apagaFilme.html', context)

def editaFilmeView(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('deveAutenticar')
    filme = get_object_or_404(Filme, slug=slug)
    if request.POST:
        form = AtualizaFilmeForm(request.POST or None, request.FILES or 
                                 None, instance=filme)
        if form.is_valid():
            objeto = form.save(commit=False)
            objeto.save()
            messages.success(request, 'Informações do filme atualizadas!')
            filme = objeto
            return redirect('home')
        
    form = AtualizaFilmeForm(
        initial= {
            "titulo": filme.titulo,
            "nacionalidade": filme.nacionalidade,
            "ano": filme.ano,
            "sinopse": filme.sinopse,
            "diretor": filme.diretor,
            "nota": filme.nota,
            "review": filme.review,
            "visto": filme.visto
        }
    )
    context['form'] = form
    return render(request, 'filmes/editaFilme.html', context)
            

def detalhaFilmeView(request,slug):
    contexto={}
    filme=get_object_or_404(Filme,slug=slug)
    contexto['filme']=filme
    return render(request, 'filmes/detalhaFilme.html' ,contexto)

MeuSite/filmes/templates/partes/paginationFilme.html
<div class="d-flex flex-column m-auto pagination mt-5 ">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center ">

        {% if filme.has_previous %}
            <li class="page-item ">
                <a class="page-link text-bg-dark"  href="?page=1"> &laquo; Primeiro</a>
            </li>
            <li class="page-item ">
              <a class="page-link text-bg-dark" href="?page={{ filme.previous_page_number }}">&laquo; Anterior</a>
            </li>
            
        {% endif %}
    
        {% for i in filme.paginator.page_range %}
            {% if filme.number == i %}
                <li class="page-item active "><a class="page-link ">{{ i }}</a></li>
            {% else %}
                <li class="page-item " ><a class="page-link text-bg-dark" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if filme.has_next %}
            <li class="page-item">
              <a class="page-link text-bg-dark" href="?page={{ filme.next_page_number }}">Próximo</a>
            </li>
            <li class="page-item">
              <a class="page-link text-bg-dark"  href="?page={{ filme.paginator.num_pages }}">Último &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>

MeuSite/filmes/templates/partes/partesFilme.html
<div class="container">
    <div class="row">
        <div class="card m-auto text-bg-dark">
            <div class="card-body my-2">
                <div class="d-flex justify-content-between align-items-center">
                    <h2 class="card-titulo">{{filme.titulo}}</h2>
                </div>
                <hr>
                <a href='{% url 'filmes:detalha' filme.slug %}' style="text-decoration: none !important" class=" link-dark">
                    <div class="container">
                        <p class="card-text text-bg-dark">{{filme.titulo}}</p>
                        <p class="card-text text-bg-dark"> Nota: {{filme.nota}}</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>